better error handling

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -22,8 +22,17 @@ if [ -f $ENV_DIR/ENVKEY ]; then
   tar zxf envkey-source.tar.gz envkey-source
 
   export "ENVKEY=$(cat $ENV_DIR/ENVKEY)"
-  echo $(./envkey-source) > $BP_DIR/export
-  echo "EnvKey variables exported" | indent
+  OUTPUT=$(./envkey-source)
+
+  if [[ $OUTPUT == "echo 'error:"* ]] ; then
+    eval $OUTPUT | indent
+    exit 1
+  else
+    echo $OUTPUT > $BP_DIR/export
+    echo "EnvKey variables exported" | indent
+  fi
+
+
 else
   echo "ENVKEY config var not set" | indent
   exit 1
